### ISSUE TITLE
Support PHP 7.3

### ISSUE THREAD

**Issue by ffalkone** [Eurotext/magento2-translation-manager#1]
Hello,

the new Magento Version 2.3.4 recommends using PHP 7.3 - can you please provide an updated Version that also supports PHP 7.3. Thanks

- https://github.com/Eurotext/PHP-REST-API-Client/pull/1
- https://github.com/Eurotext/magento2-translation-manager/pull/2
- https://github.com/Eurotext/magento2-translation-manager-product/pull/1
- https://github.com/Eurotext/magento2-translation-manager-eav/pull/1
- https://github.com/Eurotext/magento2-translation-manager-category/pull/1

Best Regards
Falk

**Comment by mwr** [comment]
thanks @ffalkone for your pull requests. They are merged now
